# ===================================================================
# Spring Boot configuration.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
  port: 8080

spring:
  application:
    name: image-textract-processor

  # database connection properties
  # changed when running on docker with env vars
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: image-textract-processor
      auto-index-creation: false

  # other config
  messages:
    basename: i18n/messages

# Spring Boot Actuator
management:
  endpoint:
    health:
      enabled: true

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration
# ===================================================================

application:
  aws:
    # must be set at application start or with environment variables
    region: us-east-1
    access-key-id: some-access-key
    secret-access-key: some-secret-key
    s3-source-bucket: the-bucket-where-images-are-located
    sqs-queue: the-sqs-queue-name.fifo # all sqs fifo queues must have .fifo in the end
  files:
    source-prefix: textract/

