# ===================================================================
# Spring Boot configuration.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
  port: 8080

spring:
  application:
    name: spring-jms-with-aws-sqs-fifo

  # datasource config
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/sirec
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.id.new_generator_mappings: true
      hibernate.generate_statistics: false
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.hbm2ddl.auto: none
    open-in-view: true

  # other config
  messages:
    basename: i18n/messages

# Spring Boot Actuator
management:
  endpoint:
    health:
      enabled: true

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration
# ===================================================================

application:
  aws:
    # must be set at application start or with environment variables
    region: us-east-1
    access-key-id: # must be set at application start or with environment variables
    secret-access-key: # must be set at application start or with environment variables
    s3-source-bucket: # must be set at application start or with environment variables
    sqs-queue: # must be set at application start or with environment variables
  files:
    source-prefix: textract/

